name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 5.0.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Opam
        uses: fangyi-zhou/actions-ocaml@v1
        with:
          ocaml_version: 5.0.0
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v4
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: eval $(opam config env)
      - run: dune build bin/main.bc.js --profile="release"

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
      
